### ISSUE TITLE
'composer drupal-update' returns 'Your requirements could not be resolved to an installable set of packages.'

### ISSUE THREAD

**Issue by Ben-Coleman** [dpi/avatars#12]
Using Composer Manager  8.x-1.0-rc1 (which appears to be as up-to-date as the current -dev) and Avatar Kit 8.x-1.0-alpha5, running 'composer drupal-update' from the site root  returns:

> Your requirements could not be resolved to an installable set of packages.
>   Problem 1
>     - The requested package guzzlehttp/guzzle ~5.0 could not be found.

An examination of Avatar Kit's  composer.json shows it is indeed asking for guzzlehttp/guzzle ~5.0

**Comment by dpi** [comment]
Actually Ill be pushing an update later today! You do not actually need composer manager anymore as there is no longer any external dependencies.

It is safe to remove the requirement from info.yml

**Comment by Ben-Coleman** [comment]
I presume you mean that I can just remove Avatar Kit's composer.json?  Or at least remove that requirement from there?  I see no requirement for guzzlehttp/guzzle in the info.yml

**Comment by dpi** [comment]
~~Yep both~~ Just the composer.json

Turns out I had the changes locally, I'm pushing them now.

**Comment by dpi** [comment]
New release tagged and pushed on D.O: https://www.drupal.org/node/2609598

**Comment by Ben-Coleman** [comment]
Excellent!
