### ISSUE TITLE
PNG images saved as JPG

### ISSUE THREAD

**Issue by sitarane** [dpi/avatars#29]
Using Avatar Kit (https://www.drupal.org/project/avatars) on my Drupal 8 site, I can't get the saved avatars to actually display anywhere. The preview in /user/edit displays fine, but when I go to the View tab, It only shows a string with the name of the service I picked (Robohash) where the image should be. Same if I switch service.

After a bit of digging, I find that the files saved by the module in /sites/default/files/avatar_kit/robohash are indeed there. They have .jpg extensions (19.jpg) and fail to open. But if I rename them ending in .png (19.png), they open fine and show robot avatars.

So, the module apparently retrieves png files from the service to display in the user profile edit. Once the avatar is selected by the user and the page saved, the files are saved to the file system as .jpg, making them unusable.

Also, there is no "avatars" tag on Drupal Answers.

**Comment by dpi** [comment]
The extension of the file shouldn't make any difference at all. There could be no extension, or something irrelevant like `.txt`

I understand saving with a .jpg suffix is an aesthetic issue, and I can address this. I fail to see why this is causing an issue when displaying the file in a web browser?

**Comment by dpi** [comment]
> Also, there is no "avatars" tag on Drupal Answers.

Thanks for the heads up

**Comment by dpi** [comment]
>  It only shows a string with the name of the service I picked (Robohash) where the image should be.

This doesn't sound right... Depending on which install profile you use, the picture may not show by default in some places. Can you make sure the user picture field formatter is activated. 

Post a screenshot if you continue to have issues...
