### ISSUE TITLE
Can't access setting page (8.x-1.0-beta4 & dev)

### ISSUE THREAD

**Issue by mwetmore** [dpi/avatars#32]
Hello, after installing the Avatar module on a relatively clean 8.1.7 core, I'm receiving the error below when visiting /admin/config/people/avatars the following error is thrown...

`InvalidArgumentException: Class "\Drupal\avatars\Form\Settings" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 24 of /mnt/www/html/drupalcampctdev/docroot/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php).`

I have tried both the Beta and the current Dev without any success.  

Any idea what the problem might be?

Thanks!

**Comment by dpi** [comment]
I cant say I've seen this before.

**Try:**
- Cache clear?
- Check _modules/avatars/src/Form/Settings.php_ exists
- Perhaps your Composer is hosed? Delete your vendor dir and update?
- Maybe a third party module is interacting strangely?

**Comment by mwetmore** [comment]
Yeah, it's really weird, I cleared cache, /modules/avatars/src/Form/Settings.php exists, and I reinstalled vendor dir, same issue, will have to spend some more time tomorrow digging into it

**Comment by dpi** [comment]
Hmm.

I see this error after enabling on Drush. Cache clear fixed it.

Drupal VM
Drush v8.1.12 (latest stable)
Installed via composer, prefer souce, checked out HEAD===beta5
Core 8.3.5 (latest stable)
