### ISSUE TITLE
Can't uninstall module

### ISSUE THREAD

**Issue by rroose** [dpi/avatars#33]
The module prevents me from uninstalling because of the following:
"There is content for the entity type: Avatar preview"

How to remove the content in this this entity type?

**Comment by dpi** [comment]
You can either delete all the rows from the _{avatar_preview}_ table, or if you are using Drupal 8.2 or later, you can go to _/admin/modules/uninstall_ then use the **Remove avatar preview entities** button (see figure).

![unins](https://cloud.githubusercontent.com/assets/21850/17804122/c503d672-662c-11e6-817a-4b60fbcc6b51.jpg)
