### ISSUE TITLE
Unable to uninstall 

### ISSUE THREAD

**Issue by huahaiy** [dpi/avatars#44]
> Drupal\Core\Extension\ModuleUninstallValidatorException: The following reasons prevent the modules from being uninstalled: There is content for the entity type: Avatar preview. <a href="/admin/modules/uninstall/entity/avatars_preview">Remove avatar preview   [error]
> entities</a>. in /homepages/37/d90118448/htdocs/drupal/core/lib/Drupal/Core/Extension/ModuleInstaller.php:358
> Stack trace:
> #0 /homepages/37/d90118448/htdocs/drupal/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(91): Drupal\Core\Extension\ModuleInstaller->uninstall(Array, true)
> #1 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/commands/core/drupal/environment.inc(227): Drupal\Core\ProxyClass\Extension\ModuleInstaller->uninstall(Array)
> #2 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/commands/core/drupal/pm_8.inc(79): drush_module_uninstall(Array)
> #3 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/commands/pm/pm.drush.inc(1250): _drush_pm_uninstall(Array)
> #4 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/includes/command.inc(422): drush_pm_uninstall('avatars')
> #5 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
> #6 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/includes/command.inc(199): drush_command('avatars')
> #7 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
> #8 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
> #9 /homepages/37/d90118448/htdocs/drupal/vendor/drush/drush/drush.php(12): drush_main()
> #10 {main}
>

**Comment by dpi** [comment]
See #33
