### ISSUE TITLE
PHP fatal error when trying to remove service

### ISSUE THREAD

**Issue by dsnopek** [dpi/avatars#46]
I have avatars and avatars_gravatar both at the latest 2.x-dev version. When attempting to remove one of the services from avatars_gravatar, I get this error:

```
"NOTICE: PHP message: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Route "entity.avatars_service.canonical" does not exist." at /app/web/core/lib/Drupal/Core/Routing/RouteProvider.php line 190
```

**Comment by dpi** [comment]
Cannot reproduce this one.

Ive seen this error occur when a third party module incorrect expects every entity to (a) implement routes (b) or, have a route named "canonical"

**Comment by socialnicheguru** [comment]
I have this happening on my machine. it is very frustrating. how do I uninstall this module. This is for 2.x.

**Comment by dpi** [comment]
2.x is now EOL.
