### ISSUE TITLE
Add note that 2.x branch is not compatible with webflo/drupal-core-strict

### ISSUE THREAD

**Issue by ptmkenny** [dpi/avatars#49]
Avatar 2.x requires dpi/ak, which requires  "doctrine/annotations": "^1.5",

At least currently, as of core 8.6.12, webflo/drupal-core-strict (suggested by drupal.org composer file) locks doctrine/annotations at 1.2.7, which means the 2.x branch of this module can't be installed.

Since use of weblo/drupal-core-strict is a fairly common configuration, it might be useful to have a note that this has to be removed to install the 2.x branch of avatar.

**Comment by dpi** [comment]
2.x is now EOL.
