### ISSUE TITLE
Drupal 9 plan?

### ISSUE THREAD

**Issue by goba** [dpi/avatars#50]
The project page says "Avatar Kit follows Drupal 9 and Drupal 8 head with best effort, feel free to file issues.". The latest release is 8.x-1.0 from 2017 and is of course not Drupal 9 compatible. I see 2.x development is paused. Unfortunately https://dev.acquia.com/drupal9/deprecation_status?names=%2Aavatar%2A picks up 2.x as the latest version, so I don't know what are the 1.x deprecation errors. Is there a plan to release a Drupal 9 compatible version of 1.x or 2.x?

Thanks!

**Comment by dpi** [comment]
Thanks @goba, 1.x is now ready for use with D9. 2.x remains EOL.
